- name: filters demo
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Suresh') }}"
  - name: string convert to list
    vars:
      fruits: "apple,banana,peers"
    ansible.builtin.debug:
      msg: "Fruits are {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        subject: Devops
        trainer: reddy
        duration: 120
    ansible.builtin.debug:
      msg: "the course info: {{ course | dict2items }}"

  - name: convert lst into map
    vars:
      course:
        - { 'key': 'name', 'value': 'jai' }
        - { 'key': 'sal', 'value': '1000' }
    ansible.builtin.debug:
      msg: "course info {{ course | items2dict }}"

  - name: convert name to upper case
    vars:
      name: "jai"
    ansible.builtin.debug:
      msg: "name in upper case {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "JAYARAM"
    ansible.builtin.debug:
      msg: " name in lower case: {{ name | lower }}"

  - name: find min and max
    vars:
      numbers: [23,12,1,34,45,33]
    ansible.builtin.debug:
      msg: "min num is: {{ numbers | min }} and max num is {{ numbers | max }}"

  - name: check valid ip address
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"


