- name: filters demo
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Suresh') }}"
  - name: string convert to list
    vars:
      fruits: "apple,banana,peers"
    ansible.builtin.debug:
      msg: "Fruits are {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        subject: "Devops"
        trainer: "reddy"
        duration: 120
    ansible.builtin.debug:
      msg: "the course is: {{ course | items2dict }}"